spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:file:./kotlin-tuto/db-user
    data-username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
